#+TITLE: pkg_diff run
this document discribes how pkg_diff runs and what is does._
* Intro 
Everything is set up as module. For example the source download part is just a module 
that contains other modules.
* Init 
** Config 
First config is readed either of: 
#+BEGIN_SRC sh
$HOME/.config/pkg_diff.conf
#+END_SRC
or
#+BEGIN_SRC sh
$PWD/.pkg_diff.conf
#+END_SRC
Or nowhere if none of them are present.
For it's content see: [[./config.org][config]]
** Parse Options
Then options are parsed as described in the options files in /src/options/.
For an example see [[./structure.org::Example][here]]

First the /args/ var is stored in the global args var, 
same as for the arg_func var.

Than the actual arguments are taken and checked if 
valid against the parsed /args/.

After this all parsed arg func are called to do their job for each parsed arg.
* Run
There's no difference between local and remote source anymore. Each source is prepared
and than compared against each other.
The source can be vcs, a set of remote files or a local. 

* Destroy/End
Remove downloaded target dirs.

